import { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, TextInput, View } from 'react-native';
import { createModifierGroup, deleteModifierGroup, listModifierGroups, updateModifierGroup } from '../src/auth/auth-client';
import { lightColors } from '../src/design/tokens';

export default function ModifiersScreen() {
  const [groups, setGroups] = useState<Awaited<ReturnType<typeof listModifierGroups>>>([]);
  const [name, setName] = useState(''); const [option, setOption] = useState(''); const [price, setPrice] = useState(''); const [editingId, setEditingId] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  const reload = () => listModifierGroups().then(setGroups).finally(() => setLoading(false));
  useEffect(() => { void reload(); }, []);
  const save = async () => { setMessage(''); try { const current = groups.find((group) => group.id === editingId); const input = { name, required: false, minSelections: 0, maxSelections: 1, options: [{ id: current?.options[0]?.id, name: option, priceDelta: { amount: price || '0', currency: 'LAK' as const } }] }; if (editingId) await updateModifierGroup(editingId, input); else await createModifierGroup(input); setName(''); setOption(''); setPrice(''); setEditingId(null); setMessage('ບັນທຶກສຳເລັດ'); await reload(); } catch { setMessage('ບັນທຶກບໍ່ສຳເລັດ'); } };
  return <View style={styles.page}><Text style={styles.title}>Modifier</Text><View style={styles.card}><TextInput placeholder="ຊື່ກຸ່ມ ເຊັ່ນ ຄວາມຫວານ" value={name} onChangeText={setName} style={styles.input} /><TextInput placeholder="ຕົວເລືອກ" value={option} onChangeText={setOption} style={styles.input} /><TextInput placeholder="ລາຄາເພີ່ມ" value={price} onChangeText={setPrice} keyboardType="number-pad" style={styles.input} /><Text style={styles.button} onPress={() => void save()}>{editingId ? 'ອັບເດດ Modifier' : '+ ສ້າງ Modifier'}</Text>{message ? <Text style={styles.message}>{message}</Text> : null}</View>{loading ? <ActivityIndicator /> : groups.map((group) => <View style={styles.row} key={group.id}><Text style={styles.name}>{group.name}</Text><Text style={styles.meta}>{group.options.map((item) => item.name).join(' · ')}</Text><Text style={styles.link} onPress={() => { setEditingId(group.id); setName(group.name); setOption(group.options[0]?.name ?? ''); setPrice(String(group.options[0]?.priceDeltaAmount ?? '0')); }}>ແກ້ໄຂ</Text><Text style={styles.delete} onPress={() => void deleteModifierGroup(group.id).then(reload).catch(() => setMessage('ລຶບບໍ່ໄດ້: Modifier ນີ້ມີປະຫວັດການຂາຍ'))}>ລຶບ</Text></View>)}</View>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: lightColors.background, padding: 22 }, title: { fontSize: 25, fontFamily: 'NotoSansLao_700Bold', color: lightColors.text, marginBottom: 18 }, card: { backgroundColor: lightColors.surface, borderRadius: 14, padding: 14, gap: 8, marginBottom: 14 }, input: { borderWidth: 1, borderColor: lightColors.border, borderRadius: 10, padding: 10, color: lightColors.text }, button: { backgroundColor: lightColors.primary, color: '#fff', textAlign: 'center', padding: 12, borderRadius: 10 }, message: { color: lightColors.primary }, row: { backgroundColor: lightColors.surface, padding: 14, borderRadius: 12, marginBottom: 8 }, name: { color: lightColors.text, fontFamily: 'NotoSansLao_700Bold' }, meta: { color: lightColors.textMuted, marginTop: 4 }, link: { color: lightColors.primary, marginTop: 8 }, delete: { color: '#B42318', marginTop: 4 } });
