import { FlashList } from '@shopify/flash-list';
import { ReceiptText, Share2, Printer, Search } from 'lucide-react-native';
import { useEffect, useState } from 'react';
import { Alert, Modal, Pressable, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import { lightColors } from '../src/design/tokens';
import { listEmployees, listReceipts, refundOrder } from '../src/auth/auth-client';

type Receipt = { id: string; number: string; createdAt: string; order: { id: string; totalAmount: string; status: string; employee?: { name: string }; payments: Array<{ unverified: boolean }> } };
const formatLak = (amount: string | number) => `${Number(amount).toLocaleString('en-US')} ₭`;
export default function ReceiptsScreen() {
  const router = useRouter();
  const [rows, setRows] = useState<Receipt[]>([]);
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [refundReceipt, setRefundReceipt] = useState<Receipt | null>(null);
  const [managerEmployeeId, setManagerEmployeeId] = useState('');
  const [managerPin, setManagerPin] = useState('');
  const [reason, setReason] = useState('');
  const load = async (search?: string) => { setLoading(true); try { setRows(await listReceipts(search)); } catch (error) { Alert.alert('ໂຫຼດໃບເສັດບໍ່ສຳເລັດ', error instanceof Error ? error.message : 'ລອງໃໝ່'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const openRefund = async (receipt: Receipt) => { try { const employees = await listEmployees(); const manager = employees.find((employee) => employee.role === 'MANAGER' && employee.active) ?? employees.find((employee) => employee.role === 'OWNER' && employee.active); setManagerEmployeeId(manager?.id ?? ''); setRefundReceipt(receipt); } catch (error) { Alert.alert('ບໍ່ສາມາດເລີ່ມຄືນເງິນ', error instanceof Error ? error.message : 'ລອງໃໝ່'); } };
  const submitRefund = async () => { if (!refundReceipt || !managerEmployeeId || !managerPin || !reason.trim()) return; try { await refundOrder({ orderId: refundReceipt.order.id, managerEmployeeId, managerPin, reason: reason.trim() }); setRefundReceipt(null); setManagerPin(''); setReason(''); await load(query); Alert.alert('ຄືນເງິນສຳເລັດ'); } catch (error) { Alert.alert('ຄືນເງິນບໍ່ສຳເລັດ', error instanceof Error ? error.message : 'ກວດສອບ Manager PIN'); } };
  return <View style={styles.page}>
    <View style={styles.header}><Pressable onPress={() => router.replace('/')}><Text style={styles.back}>‹</Text></Pressable><View><Text style={styles.title}>ໃບເສັດ</Text><Text style={styles.subtitle}>{loading ? 'ກຳລັງໂຫຼດ...' : `${rows.length} ໃບຫຼ້າສຸດ`}</Text></View></View>
    <View style={styles.search}><Search size={19} color={lightColors.textMuted} /><TextInput value={query} onChangeText={setQuery} onSubmitEditing={() => void load(query)} placeholder="ຄົ້ນຫາເລກໃບເສັດ" placeholderTextColor={lightColors.textMuted} style={styles.searchInput} /></View>
    <FlashList data={rows} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => <View style={styles.card}><View style={styles.cardMain}><ReceiptText color={lightColors.primary} size={21} /><View><Text style={styles.number}>{item.number}</Text><Text style={styles.meta}>{new Date(item.createdAt).toLocaleString('lo-LA')} · {item.order.employee?.name ?? '—'}</Text><Text style={styles.amount}>{formatLak(item.order.totalAmount)} · {item.order.status === 'REFUNDED' ? 'ຄືນເງິນ' : item.order.payments[0]?.unverified ? 'QR ບໍ່ຢືນຢັນ' : 'ຈ່າຍແລ້ວ'}</Text></View></View><View style={styles.actions}><Pressable onPress={() => Alert.alert('ພິມຊ້ຳ', 'ໃບເສັດຖືກກຽມສົ່ງໃຫ້ເຄື່ອງພິມ')}><Printer size={19} color={lightColors.text} /></Pressable><Pressable onPress={() => void Share.share({ message: `Sunha POS\n${item.number}\nຍອດລວມ: ${formatLak(item.order.totalAmount)}` })}><Share2 size={19} color={lightColors.text} /></Pressable>{item.order.status === 'COMPLETED' ? <Pressable onPress={() => void openRefund(item)}><Text style={styles.refund}>ຄືນ</Text></Pressable> : null}</View></View>} />
    <Modal visible={Boolean(refundReceipt)} transparent animationType="fade"><View style={styles.refundBackdrop}><View style={styles.refundBox}><Text style={styles.refundTitle}>ຄືນເງິນເຕັມໃບເສັດ</Text><TextInput value={managerPin} onChangeText={setManagerPin} keyboardType="number-pad" secureTextEntry placeholder="Manager PIN 6 ຕົວ" style={styles.refundInput} /><TextInput value={reason} onChangeText={setReason} placeholder="ເຫດຜົນ" style={styles.refundInput} /><Pressable style={styles.refundButton} onPress={() => void submitRefund()}><Text style={styles.refundButtonText}>ຢືນຢັນຄືນເງິນ</Text></Pressable><Pressable onPress={() => setRefundReceipt(null)}><Text style={styles.cancel}>ຍົກເລີກ</Text></Pressable></View></View></Modal>
  </View>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: lightColors.background, padding: 16 }, header: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 15 }, back: { fontSize: 36, color: lightColors.text, lineHeight: 36 }, title: { fontFamily: 'NotoSansLao_700Bold', fontSize: 21, color: lightColors.text }, subtitle: { fontFamily: 'NotoSansLao_400Regular', fontSize: 11, color: lightColors.textMuted }, search: { height: 46, borderWidth: 1, borderColor: lightColors.border, borderRadius: 14, backgroundColor: lightColors.surface, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, gap: 8, marginBottom: 10 }, searchInput: { flex: 1, fontFamily: 'NotoSansLao_400Regular', color: lightColors.text, fontSize: 13 }, list: { paddingBottom: 20 }, card: { backgroundColor: lightColors.surface, borderWidth: 1, borderColor: lightColors.border, borderRadius: 16, padding: 13, marginBottom: 9, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, cardMain: { flexDirection: 'row', alignItems: 'center', gap: 11, flex: 1 }, number: { fontFamily: 'NotoSansLao_700Bold', fontSize: 13, color: lightColors.text }, meta: { fontFamily: 'NotoSansLao_400Regular', fontSize: 10, color: lightColors.textMuted, marginTop: 2 }, amount: { fontFamily: 'NotoSansLao_700Bold', fontSize: 12, color: lightColors.primary, marginTop: 3 }, actions: { flexDirection: 'row', gap: 16, paddingLeft: 8 }, refund: { fontFamily: 'NotoSansLao_700Bold', fontSize: 11, color: '#B42318' }, refundBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'center', padding: 18 }, refundBox: { backgroundColor: lightColors.surface, borderRadius: 20, padding: 18, gap: 12 }, refundTitle: { fontFamily: 'NotoSansLao_700Bold', color: lightColors.text, fontSize: 17 }, refundInput: { minHeight: 46, borderWidth: 1, borderColor: lightColors.border, borderRadius: 12, paddingHorizontal: 12, color: lightColors.text, fontFamily: 'NotoSansLao_400Regular' }, refundButton: { minHeight: 48, backgroundColor: lightColors.primary, borderRadius: 13, justifyContent: 'center', alignItems: 'center' }, refundButtonText: { color: lightColors.onPrimary, fontFamily: 'NotoSansLao_700Bold' }, cancel: { textAlign: 'center', color: lightColors.textMuted, fontFamily: 'NotoSansLao_400Regular' } });
