import { useEffect, useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { createTax, deleteTax, listTaxes, updateTax } from '../src/auth/auth-client';
import { lightColors } from '../src/design/tokens';

export default function TaxesScreen() {
  const [taxes, setTaxes] = useState<Awaited<ReturnType<typeof listTaxes>>>([]); const [name, setName] = useState('VAT'); const [rate, setRate] = useState('700'); const [editingId, setEditingId] = useState<string | null>(null); const reload = () => listTaxes().then(setTaxes); useEffect(() => { void reload(); }, []);
  const save = async () => { const input = { name, rateBasisPoints: Number(rate), mode: 'EXCLUSIVE' as const }; if (editingId) await updateTax(editingId, input); else await createTax(input); setEditingId(null); setName('VAT'); setRate('700'); await reload(); };
  return <View style={styles.page}><Text style={styles.title}>ພາສີ</Text><View style={styles.card}><TextInput value={name} onChangeText={setName} placeholder="ຊື່ພາສີ" style={styles.input} /><TextInput value={rate} onChangeText={setRate} placeholder="basis points" keyboardType="number-pad" style={styles.input} /><Text style={styles.button} onPress={() => void save()}>{editingId ? 'ອັບເດດພາສີ' : '+ ເພີ່ມພາສີ'}</Text></View>{taxes.map((tax) => <View style={styles.row} key={tax.id}><Text style={styles.name}>{tax.name}</Text><Text style={styles.meta}>{(tax.rateBasisPoints / 100).toFixed(2)}% · {tax.mode}</Text><Text style={styles.link} onPress={() => { setEditingId(tax.id); setName(tax.name); setRate(String(tax.rateBasisPoints)); }}>ແກ້ໄຂ</Text><Text style={styles.delete} onPress={() => void deleteTax(tax.id).then(reload)}>ປິດໃຊ້ງານ</Text></View>)}</View>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: lightColors.background, padding: 22 }, title: { fontSize: 25, fontFamily: 'NotoSansLao_700Bold', color: lightColors.text, marginBottom: 18 }, card: { backgroundColor: lightColors.surface, borderRadius: 14, padding: 14, gap: 8, marginBottom: 14 }, input: { borderWidth: 1, borderColor: lightColors.border, borderRadius: 10, padding: 10, color: lightColors.text }, button: { backgroundColor: lightColors.primary, color: '#fff', textAlign: 'center', padding: 12, borderRadius: 10 }, row: { padding: 14, backgroundColor: lightColors.surface, borderRadius: 12, marginBottom: 8 }, name: { fontFamily: 'NotoSansLao_700Bold', color: lightColors.text }, meta: { color: lightColors.textMuted }, link: { color: lightColors.primary, marginTop: 8 }, delete: { color: '#B42318', marginTop: 4 } });
